name: Node.js CI

on:
  push:
    branches: ['master']

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3.5.0
        with:
          node-version: 20
          registry-url: https://registry.npmjs.org
          cache: 'npm'
      - run: node --version
      - run: npm --version
      - run: npm cache clean --force
      - name: Install Node Dependencies
        run: npm install --no-package-lock
      - name: Build Chrome
        run: npm run build:chrome
      - name: Build Firefox
        run: npm run build:firefox
      - name: Post Lint Firefox
        run: npm run manifest-lint
      - name: Build User-Script
        run: npm run build:userscript
