name: Node.js CI

on:
  push:
    branches: ['master']

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          registry-url: https://registry.npmjs.org
          cache: 'npm'
      - run: node --version
      - run: npm --version
      - run: npm cache clean --force
      - name: Install Node Dependencies
        run: npm install --no-package-lock
      - name: Build All
        run: npm run build
