name: Node.js CI

on:
  push:
    branches: ['master']

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          registry-url: https://registry.npmjs.org
          cache: 'npm'
      - run: node --version
      - run: npm --version
      - run: npm cache clean --force
      - name: Install Node Dependencies
        run: npm install --no-package-lock
        
      - name: Build Userscript
        run: npm run build:userscript

      - name: Package All
        run: npm run package
        
      - name: Clear build folder
        run: |
          rm -rf build
          mkdir build

      - name: Copy built files to build folder
        run: cp -r ./dist/* build/
  
      - name: Commit build folder
        uses: EndBug/add-and-commit@v7
        with:
          add: build
          message: 'Update build folder'
          push: true
  
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.get_version.outputs.version }}
          release_name: Release ${{ steps.get_version.outputs.version }}
          draft: false
          prerelease: false

      - name: Get version
        id: get_version
        run: echo "version=$(node -p -e "require('./package.json').version")"
