name: Node.js CI

on:
  push:
    branches: ['master']

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
        with:
          ref: master
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          registry-url: https://registry.npmjs.org
          cache: 'npm'
      - run: node --version
      - run: npm --version
      - run: npm cache clean --force
      - name: Install Node Dependencies
        run: npm install --no-package-lock
        
      - name: Build Userscript
        run: npm run build:userscript

      - name: Package All
        run: npm run package
        
      - name: Get version
        id: get_version
        run: |
          VERSION=$(node -p "require('./package.json').version")
          echo "VERSION=$VERSION" >> $GITHUB_ENV

      - name: Version data
        run: |
            echo "Version: ${{ env.VERSION }}"

      - name: Create Release
        id: create_release
        uses: softprops/action-gh-release@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          tag_name: v${{ env.VERSION }}
          files: dist/*
